step3 10950 A+B-3 and ReadMe Updates
mtak0235/helloPython pull request #18
Opened 2022-01-17 13:53 UTC by DBrider3

잘부탁드립니다. 첫 pr!

2022-01-17 14:54 UTC, Arkingco commented
가즈아~

2022-01-17 15:13 UTC, TARK-YEJI commented
우와...개발자 자기소개서는 다 이 정도는 하는 건가요..!?!?
 더 열심히 살아야겠다는 생각이 들었습니다.

2022-01-18 03:43 UTC, Sara-Jo commented
정성넘치는 자기소개 최고에요...고생하셨어요!

2022-01-21 05:38 UTC, mtak0235 requested changes

2022-01-21 05:38 UTC, mtak0235 commented on step4/dcho/a+b-4.py
> +	if (a < 0 or a > 10 or b < 0 or b > 10):
a가 0보다 큰 양수가 들어오고, b는 10보다 작은 정수가 들어오는데 해당 if문에서는 a가 10보다 클 경우에 거르면 안되는데 break로 걸러버려서,  백준에 있는 예문은 통과했지만, 문제 조건에 맞지 않아 fail이 뜬 것 같습니다!

2022-01-21 05:38 UTC, mtak0235 commented on step4/dcho/a+b-4.py
> +	if (a < 0 or a > 10 or b < 0 or b > 10):
또 b는 10보다 작기만 하면 다 통과해야하는데,  해당 코드에선 b가 음수일 떄 걸러버려서, 문제 조건에 맞지 않습니당

2022-01-21 05:38 UTC, mtak0235 commented on step4/dcho/a+b-4.py
> +while i < 5:
for i in range(5):를 사용하시면 코드가 더 심플해 질 것 같아욥! 고생하셨습니다 ㅎㅎ

2022-01-21 05:41 UTC, mtak0235 commented on step4/dcho/a+b-4.py
> +	if (a < 0 or a > 10 or b < 0 or b > 10):
제가 문제를 다시 째려보니, 입력 라인을 몇개 준다고 이야기한적이 없더군요! 아무래도 무한루프 돌리셔야 할 것 같습다!

2022-01-29 09:26 UTC, mtak0235 approved these changes

2022-01-29 09:26 UTC, mtak0235 commented on step3/dcho/a+b-7+.py
> +for	i in range(0, number):
range(number) == range(0,number) //true(끄덕)

2022-01-29 09:26 UTC, mtak0235 commented on step5/dcho/1546.py
> +for index, value in enumerate(onelist):
enumerate(메모..)

2022-01-29 09:26 UTC, mtak0235 commented on step6/dcho/15596.py
> +	for value in a: ans += value
대괄호 없이 for문 한 줄 쓰기 (메모

2022-01-30 10:53 UTC, merged